from fastapi import APIRouter, Depends, HTTPException, status
from fastapi.responses import StreamingResponse
from sqlalchemy.orm import Session
import io
from typing import List
from app.core.database import get_db
from app.core.security import get_current_user
from app.models.models import Report, HistoricalAQI, User
from app.schemas.schemas import ReportResponse
from app.agents.report_agent import ReportGenerationAgent

router = APIRouter(prefix="/api/reports", tags=["Analytical Reports"])
report_agent = ReportGenerationAgent()

@router.post("/generate", response_model=ReportResponse)
def generate_report(
    report_type: str = "Weekly", # Weekly, Monthly, Yearly
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """
    Triggers the Report Agent. Collects environmental history, performs aggregates,
    calls LLM for executive summaries, and records the report metadata in the database.
    """
    # Fetch historical readings for aggregates
    history = db.query(HistoricalAQI).order_by(HistoricalAQI.timestamp.desc()).limit(1000).all()
    
    if not history:
        raise HTTPException(
            status_code=400,
            detail="Insufficient historical records available to generate report."
        )
        
    analysis = report_agent.generate_analytical_report(history, report_type)
    
    # Save report to DB
    new_report = Report(
        user_id=current_user.id,
        title=analysis["title"],
        type=report_type,
        file_path=f"downloads/report_{report_type.lower()}_{int(pd.Timestamp.now().timestamp()) if 'pd' in globals() else 1234}.csv",
        summary=analysis["executive_summary"]
    )
    db.add(new_report)
    db.commit()
    db.refresh(new_report)
    
    return new_report

@router.get("/list", response_model=List[ReportResponse])
def list_reports(current_user: User = Depends(get_current_user), db: Session = Depends(get_db)):
    """
    Lists all reports generated by/for municipal admins.
    If empty, pre-seeds a few mock reports.
    """
    reports = db.query(Report).order_by(Report.created_at.desc()).all()
    
    if not reports:
        # Pre-seed a few mock entries for the dashboard
        r1 = Report(
            user_id=current_user.id,
            title="Prana City Environmental Performance Audit - Q1",
            type="Monthly",
            file_path="downloads/report_q1_audit.csv",
            summary="A comprehensive Q1 audit showing critical PM2.5 hotspots in Ward 3 and Ward 5. Traffic mitigation policies achieved an average 12% AQI reduction."
        )
        r2 = Report(
            user_id=current_user.id,
            title="Prana City Weekly Environmental Report",
            type="Weekly",
            file_path="downloads/report_weekly_latest.csv",
            summary="Weekly brief showing traffic congestion peaking on Mondays, corresponding to a 22% spike in particulate readings near the central corridor."
        )
        db.add_all([r1, r2])
        db.commit()
        reports = db.query(Report).order_by(Report.created_at.desc()).all()
        
    return reports

@router.get("/download/{report_id}/csv")
def download_report_csv(report_id: int, current_user: User = Depends(get_current_user), db: Session = Depends(get_db)):
    """
    Generates and downloads a CSV report of ward-by-ward air quality metrics dynamically.
    """
    report = db.query(Report).filter(Report.id == report_id).first()
    if not report:
        raise HTTPException(status_code=404, detail="Report not found.")
        
    # Generate CSV in memory
    history = db.query(HistoricalAQI).order_by(HistoricalAQI.timestamp.desc()).limit(200).all()
    
    output = io.StringIO()
    output.write("Timestamp,Ward,AQI,PM2.5,PM10,Temperature,Humidity,WindSpeed,TrafficCongestion,IndustrialEmissions\n")
    
    for row in history:
        output.write(
            f"{row.timestamp},{row.ward.name},{row.aqi},{row.pm2_5},{row.pm10},{row.temperature},{row.humidity},{row.wind_speed},{row.traffic_congestion},{row.industrial_emissions}\n"
        )
        
    output.seek(0)
    
    return StreamingResponse(
        io.BytesIO(output.getvalue().encode()),
        media_type="text/csv",
        headers={"Content-Disposition": f"attachment; filename=prana_report_{report_id}.csv"}
    )
